### ISSUE TITLE
Missing Documentation

### ISSUE THREAD

**Issue by SevenBlocks** [stekyne/PhaseVocoder#6]
Could you provide a description of how the algorithm works or a link to your thesis that this was based off of?

**Comment by stekyne** [comment]
I don't really have my thesis at hand but googling "phase vocoder overlap add" will find you a lot of relevant material.

A lot of spectral algorithms involve converting from time domain to frequency domain via FFT and then working on the magnitudes and phases from that. To do that properly, you need to segment each time domain slice, apply a window function and then perform FFT. To get it back to time domain at the end, you have to basically do the reverse. There's a bit of work in doing that but reading up overlap-add (or save) should allow you to figure it out. 

The algorithm for phase locking is based on some Moore paper but there are much more effective algorithms these days. 

This thesis looks pretty good actually for learning the theory. I think the code is in matlab though. 
https://www.spsc.tugraz.at/sites/default/files/Bachelor%20Thesis%20Gruenwald.pdf
